'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Calendar,
  Clock,
  User,
  Plus,
  Edit,
  Eye,
  Bell,
  Filter,
  ChevronLeft,
  ChevronRight,
  CalendarDays,
  Video,
  Dumbbell,
  CreditCard,
  Activity,
  AlertTriangle,
  CheckCircle,
  Settings,
  Save,
  X
} from 'lucide-react';

interface ScheduleModuleProps {
  userRole: 'trainer' | 'student';
}

interface Appointment {
  id: string;
  studentId: string;
  studentName: string;
  trainerId: string;
  trainerName: string;
  date: string;
  startTime: string;
  endTime: string;
  type: 'physical_assessment' | 'training_session' | 'online_consultation' | 'payment_due';
  status: 'scheduled' | 'completed' | 'cancelled' | 'overdue';
  observations: string;
  createdAt: string;
  isAutoGenerated?: boolean; // Para compromissos gerados automaticamente
}

interface Alert {
  id: string;
  appointmentId: string;
  type: 'assessment_due' | 'payment_due' | 'training_reminder';
  message: string;
  daysInAdvance: number;
  isActive: boolean;
  targetDate: string;
}

interface AlertSettings {
  assessmentReminder: number; // dias de antecedência
  paymentReminder: number;
  trainingReminder: number;
  enableNotifications: boolean;
}

export default function ScheduleModule({ userRole }: ScheduleModuleProps) {
  const [activeView, setActiveView] = useState<'calendar' | 'list' | 'new' | 'edit' | 'alerts' | 'settings'>('calendar');
  const [viewMode, setViewMode] = useState<'day' | 'week' | 'month'>('month');
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [selectedAppointment, setSelectedAppointment] = useState<Appointment | null>(null);
  const [filterType, setFilterType] = useState<string>('all');
  const [filterStudent, setFilterStudent] = useState<string>('all');

  // Estados para alertas e configurações
  const [alertSettings, setAlertSettings] = useState<AlertSettings>({
    assessmentReminder: 7,
    paymentReminder: 3,
    trainingReminder: 1,
    enableNotifications: true
  });

  // Dados simulados
  const [appointments, setAppointments] = useState<Appointment[]>([
    {
      id: '1',
      studentId: '1',
      studentName: 'João Silva',
      trainerId: '1',
      trainerName: 'Carlos Personal',
      date: '2024-01-20',
      startTime: '09:00',
      endTime: '10:00',
      type: 'physical_assessment',
      status: 'scheduled',
      observations: 'Avaliação física mensal - foco em composição corporal',
      createdAt: '2024-01-15T10:00:00Z'
    },
    {
      id: '2',
      studentId: '2',
      studentName: 'Maria Santos',
      trainerId: '1',
      trainerName: 'Carlos Personal',
      date: '2024-01-20',
      startTime: '14:00',
      endTime: '15:00',
      type: 'training_session',
      status: 'scheduled',
      observations: 'Treino de membros superiores',
      createdAt: '2024-01-18T14:00:00Z'
    },
    {
      id: '3',
      studentId: '3',
      studentName: 'Pedro Costa',
      trainerId: '1',
      trainerName: 'Carlos Personal',
      date: '2024-01-21',
      startTime: '16:00',
      endTime: '17:00',
      type: 'online_consultation',
      status: 'scheduled',
      observations: 'Consultoria online - ajuste do plano nutricional',
      createdAt: '2024-01-19T09:00:00Z'
    },
    {
      id: '4',
      studentId: '1',
      studentName: 'João Silva',
      trainerId: '1',
      trainerName: 'Carlos Personal',
      date: '2024-01-25',
      startTime: '23:59',
      endTime: '23:59',
      type: 'payment_due',
      status: 'scheduled',
      observations: 'Vencimento do plano Premium',
      createdAt: '2024-01-15T10:00:00Z',
      isAutoGenerated: true
    }
  ]);

  const [alerts, setAlerts] = useState<Alert[]>([
    {
      id: '1',
      appointmentId: '1',
      type: 'assessment_due',
      message: 'Avaliação física de João Silva vence em 7 dias',
      daysInAdvance: 7,
      isActive: true,
      targetDate: '2024-01-20'
    },
    {
      id: '2',
      appointmentId: '4',
      type: 'payment_due',
      message: 'Pagamento de João Silva vence em 3 dias',
      daysInAdvance: 3,
      isActive: true,
      targetDate: '2024-01-25'
    }
  ]);

  const [formData, setFormData] = useState<Partial<Appointment>>({
    date: new Date().toISOString().split('T')[0],
    startTime: '09:00',
    endTime: '10:00',
    type: 'training_session',
    status: 'scheduled',
    observations: ''
  });

  const typeLabels = {
    physical_assessment: 'Avaliação Física',
    training_session: 'Treino Presencial',
    online_consultation: 'Consultoria Online',
    payment_due: 'Vencimento de Pagamento'
  };

  const typeColors = {
    physical_assessment: 'bg-[#1FBF75]',
    training_session: 'bg-[#FFC300]',
    online_consultation: 'bg-[#E10600]',
    payment_due: 'bg-[#FF6B6B]'
  };

  const statusLabels = {
    scheduled: 'Agendado',
    completed: 'Concluído',
    cancelled: 'Cancelado',
    overdue: 'Atrasado'
  };

  const statusColors = {
    scheduled: 'bg-[#FFC300]',
    completed: 'bg-[#1FBF75]',
    cancelled: 'bg-[#4A4A4A]',
    overdue: 'bg-[#E10600]'
  };

  const handleInputChange = (field: string, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSave = () => {
    if (selectedAppointment) {
      setAppointments(prev => prev.map(appointment => 
        appointment.id === selectedAppointment.id ? { 
          ...formData, 
          id: selectedAppointment.id,
          createdAt: selectedAppointment.createdAt
        } as Appointment : appointment
      ));
    } else {
      const newAppointment: Appointment = {
        ...formData,
        id: Date.now().toString(),
        createdAt: new Date().toISOString()
      } as Appointment;
      setAppointments(prev => [...prev, newAppointment]);
      
      // Gerar alertas automáticos
      generateAutoAlerts(newAppointment);
    }
    
    setActiveView('calendar');
    setSelectedAppointment(null);
    setFormData({
      date: new Date().toISOString().split('T')[0],
      startTime: '09:00',
      endTime: '10:00',
      type: 'training_session',
      status: 'scheduled',
      observations: ''
    });
  };

  const generateAutoAlerts = (appointment: Appointment) => {
    const newAlerts: Alert[] = [];
    
    if (appointment.type === 'physical_assessment') {
      newAlerts.push({
        id: Date.now().toString() + '_1',
        appointmentId: appointment.id,
        type: 'assessment_due',
        message: `Avaliação física de ${appointment.studentName} em ${alertSettings.assessmentReminder} dias`,
        daysInAdvance: alertSettings.assessmentReminder,
        isActive: true,
        targetDate: appointment.date
      });
    }
    
    if (appointment.type === 'payment_due') {
      newAlerts.push({
        id: Date.now().toString() + '_2',
        appointmentId: appointment.id,
        type: 'payment_due',
        message: `Pagamento de ${appointment.studentName} vence em ${alertSettings.paymentReminder} dias`,
        daysInAdvance: alertSettings.paymentReminder,
        isActive: true,
        targetDate: appointment.date
      });
    }
    
    if (appointment.type === 'training_session') {
      newAlerts.push({
        id: Date.now().toString() + '_3',
        appointmentId: appointment.id,
        type: 'training_reminder',
        message: `Treino de ${appointment.studentName} amanhã às ${appointment.startTime}`,
        daysInAdvance: alertSettings.trainingReminder,
        isActive: true,
        targetDate: appointment.date
      });
    }
    
    setAlerts(prev => [...prev, ...newAlerts]);
  };

  const handleEdit = (appointment: Appointment) => {
    setSelectedAppointment(appointment);
    setFormData(appointment);
    setActiveView('edit');
  };

  const handleView = (appointment: Appointment) => {
    setSelectedAppointment(appointment);
    setActiveView('list');
  };

  const getFilteredAppointments = () => {
    return appointments.filter(appointment => {
      if (filterType !== 'all' && appointment.type !== filterType) return false;
      if (filterStudent !== 'all' && appointment.studentId !== filterStudent) return false;
      return true;
    });
  };

  const getAppointmentsForDate = (date: Date) => {
    const dateStr = date.toISOString().split('T')[0];
    return getFilteredAppointments().filter(appointment => appointment.date === dateStr);
  };

  const getActiveAlerts = () => {
    return alerts.filter(alert => alert.isActive);
  };

  const formatDate = (date: Date) => {
    return date.toLocaleDateString('pt-BR', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  const navigateDate = (direction: 'prev' | 'next') => {
    const newDate = new Date(selectedDate);
    if (viewMode === 'day') {
      newDate.setDate(newDate.getDate() + (direction === 'next' ? 1 : -1));
    } else if (viewMode === 'week') {
      newDate.setDate(newDate.getDate() + (direction === 'next' ? 7 : -7));
    } else {
      newDate.setMonth(newDate.getMonth() + (direction === 'next' ? 1 : -1));
    }
    setSelectedDate(newDate);
  };

  const renderCalendarView = () => {
    if (viewMode === 'day') {
      const dayAppointments = getAppointmentsForDate(selectedDate);
      
      return (
        <div className="space-y-4">
          <div className="text-center">
            <h3 className="text-xl font-bold text-white mb-2">
              {formatDate(selectedDate)}
            </h3>
          </div>
          
          <div className="space-y-3">
            {dayAppointments.length > 0 ? (
              dayAppointments.map(appointment => (
                <Card key={appointment.id} className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className={`w-4 h-4 rounded-full ${typeColors[appointment.type]}`}></div>
                        <div>
                          <h4 className="font-semibold text-[#0A0A0A]">{appointment.studentName}</h4>
                          <p className="text-sm text-[#4A4A4A]">
                            {appointment.startTime} - {appointment.endTime}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge className={`${typeColors[appointment.type]} text-white`}>
                          {typeLabels[appointment.type]}
                        </Badge>
                        <Button
                          size="sm"
                          onClick={() => handleView(appointment)}
                          className="bg-[#FFC300] hover:bg-[#E6C85C] text-[#0A0A0A] rounded-xl"
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))
            ) : (
              <Card className="bg-white/10 backdrop-blur-sm border-2 border-white/20 shadow-lg rounded-2xl">
                <CardContent className="p-8 text-center">
                  <Calendar className="w-12 h-12 text-white/50 mx-auto mb-4" />
                  <p className="text-white/80">Nenhum compromisso agendado para este dia</p>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      );
    }

    if (viewMode === 'week') {
      const weekStart = new Date(selectedDate);
      weekStart.setDate(weekStart.getDate() - weekStart.getDay());
      
      const weekDays = Array.from({ length: 7 }, (_, i) => {
        const day = new Date(weekStart);
        day.setDate(day.getDate() + i);
        return day;
      });

      return (
        <div className="space-y-4">
          <div className="grid grid-cols-7 gap-2">
            {weekDays.map((day, index) => {
              const dayAppointments = getAppointmentsForDate(day);
              const isToday = day.toDateString() === new Date().toDateString();
              
              return (
                <Card key={index} className={`bg-white border-2 ${isToday ? 'border-[#FFC300]' : 'border-[#E6C85C]'} shadow-lg rounded-2xl`}>
                  <CardHeader className="pb-2">
                    <div className="text-center">
                      <p className="text-xs text-[#4A4A4A]">
                        {day.toLocaleDateString('pt-BR', { weekday: 'short' })}
                      </p>
                      <p className={`text-lg font-bold ${isToday ? 'text-[#FFC300]' : 'text-[#0A0A0A]'}`}>
                        {day.getDate()}
                      </p>
                    </div>
                  </CardHeader>
                  <CardContent className="pt-0 space-y-1">
                    {dayAppointments.slice(0, 3).map(appointment => (
                      <div
                        key={appointment.id}
                        className={`p-1 rounded text-xs text-white cursor-pointer ${typeColors[appointment.type]}`}
                        onClick={() => handleView(appointment)}
                      >
                        {appointment.startTime} {appointment.studentName}
                      </div>
                    ))}
                    {dayAppointments.length > 3 && (
                      <p className="text-xs text-[#4A4A4A] text-center">
                        +{dayAppointments.length - 3} mais
                      </p>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      );
    }

    // Visualização mensal
    const monthStart = new Date(selectedDate.getFullYear(), selectedDate.getMonth(), 1);
    const monthEnd = new Date(selectedDate.getFullYear(), selectedDate.getMonth() + 1, 0);
    const startDate = new Date(monthStart);
    startDate.setDate(startDate.getDate() - startDate.getDay());
    
    const days = [];
    const current = new Date(startDate);
    
    while (current <= monthEnd || days.length < 42) {
      days.push(new Date(current));
      current.setDate(current.getDate() + 1);
      if (days.length >= 42) break;
    }

    return (
      <div className="space-y-4">
        <div className="grid grid-cols-7 gap-1 mb-4">
          {['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map(day => (
            <div key={day} className="p-2 text-center text-white font-medium">
              {day}
            </div>
          ))}
        </div>
        
        <div className="grid grid-cols-7 gap-1">
          {days.map((day, index) => {
            const dayAppointments = getAppointmentsForDate(day);
            const isCurrentMonth = day.getMonth() === selectedDate.getMonth();
            const isToday = day.toDateString() === new Date().toDateString();
            
            return (
              <Card 
                key={index} 
                className={`min-h-[100px] cursor-pointer transition-all hover:scale-105 ${
                  isCurrentMonth 
                    ? isToday 
                      ? 'bg-[#FFC300] border-2 border-[#E6C85C]' 
                      : 'bg-white border-2 border-[#E6C85C]'
                    : 'bg-gray-100 border border-gray-200'
                } shadow-lg rounded-xl`}
                onClick={() => {
                  setSelectedDate(day);
                  setViewMode('day');
                }}
              >
                <CardContent className="p-2">
                  <div className="text-center mb-1">
                    <span className={`text-sm font-medium ${
                      isCurrentMonth 
                        ? isToday 
                          ? 'text-[#0A0A0A]' 
                          : 'text-[#0A0A0A]'
                        : 'text-gray-400'
                    }`}>
                      {day.getDate()}
                    </span>
                  </div>
                  <div className="space-y-1">
                    {dayAppointments.slice(0, 2).map(appointment => (
                      <div
                        key={appointment.id}
                        className={`w-full h-1 rounded ${typeColors[appointment.type]}`}
                      />
                    ))}
                    {dayAppointments.length > 2 && (
                      <p className="text-xs text-[#4A4A4A] text-center">
                        +{dayAppointments.length - 2}
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    );
  };

  if (activeView === 'new' || activeView === 'edit') {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Calendar className="w-6 h-6 text-[#FFC300]" />
            <h2 className="text-2xl font-bold text-white">
              {activeView === 'edit' ? 'Editar' : 'Novo'} Compromisso
            </h2>
          </div>
          <Button
            onClick={() => {
              setActiveView('calendar');
              setSelectedAppointment(null);
              setFormData({
                date: new Date().toISOString().split('T')[0],
                startTime: '09:00',
                endTime: '10:00',
                type: 'training_session',
                status: 'scheduled',
                observations: ''
              });
            }}
            className="bg-white hover:bg-[#FFF3C4] text-[#0A0A0A] border-2 border-[#0A0A0A] rounded-xl"
          >
            <X className="w-4 h-4 mr-2" />
            Cancelar
          </Button>
        </div>

        <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
          <CardHeader>
            <CardTitle className="flex items-center gap-3 text-[#0A0A0A]">
              <Plus className="w-5 h-5 text-[#FFC300]" />
              Informações do Compromisso
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="studentName" className="text-[#0A0A0A] font-medium">Nome do Aluno</Label>
                <Input
                  id="studentName"
                  value={formData.studentName || ''}
                  onChange={(e) => handleInputChange('studentName', e.target.value)}
                  className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                  placeholder="Nome do aluno"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="trainerName" className="text-[#0A0A0A] font-medium">Nome do Professor</Label>
                <Input
                  id="trainerName"
                  value={formData.trainerName || ''}
                  onChange={(e) => handleInputChange('trainerName', e.target.value)}
                  className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                  placeholder="Nome do professor"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label htmlFor="date" className="text-[#0A0A0A] font-medium">Data</Label>
                <Input
                  id="date"
                  type="date"
                  value={formData.date}
                  onChange={(e) => handleInputChange('date', e.target.value)}
                  className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="startTime" className="text-[#0A0A0A] font-medium">Horário de Início</Label>
                <Input
                  id="startTime"
                  type="time"
                  value={formData.startTime}
                  onChange={(e) => handleInputChange('startTime', e.target.value)}
                  className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="endTime" className="text-[#0A0A0A] font-medium">Horário de Término</Label>
                <Input
                  id="endTime"
                  type="time"
                  value={formData.endTime}
                  onChange={(e) => handleInputChange('endTime', e.target.value)}
                  className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="type" className="text-[#0A0A0A] font-medium">Tipo de Compromisso</Label>
                <select
                  id="type"
                  value={formData.type}
                  onChange={(e) => handleInputChange('type', e.target.value)}
                  className="w-full p-3 border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300] bg-white"
                >
                  <option value="training_session">Treino Presencial</option>
                  <option value="physical_assessment">Avaliação Física</option>
                  <option value="online_consultation">Consultoria Online</option>
                  <option value="payment_due">Vencimento de Pagamento</option>
                </select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="status" className="text-[#0A0A0A] font-medium">Status</Label>
                <select
                  id="status"
                  value={formData.status}
                  onChange={(e) => handleInputChange('status', e.target.value)}
                  className="w-full p-3 border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300] bg-white"
                >
                  <option value="scheduled">Agendado</option>
                  <option value="completed">Concluído</option>
                  <option value="cancelled">Cancelado</option>
                </select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="observations" className="text-[#0A0A0A] font-medium">Observações</Label>
              <Textarea
                id="observations"
                value={formData.observations}
                onChange={(e) => handleInputChange('observations', e.target.value)}
                className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                placeholder="Observações sobre o compromisso..."
                rows={4}
              />
            </div>

            <div className="flex justify-end">
              <Button
                onClick={handleSave}
                className="bg-[#1FBF75] hover:bg-[#1AA366] text-white font-semibold px-8 py-3 rounded-2xl"
              >
                <Save className="w-5 h-5 mr-2" />
                {activeView === 'edit' ? 'Atualizar' : 'Salvar'} Compromisso
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (activeView === 'alerts') {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Bell className="w-6 h-6 text-[#FFC300]" />
            <h2 className="text-2xl font-bold text-white">Alertas e Notificações</h2>
          </div>
          <Button
            onClick={() => setActiveView('calendar')}
            className="bg-white hover:bg-[#FFF3C4] text-[#0A0A0A] border-2 border-[#0A0A0A] rounded-xl"
          >
            Voltar
          </Button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Alertas Ativos */}
          <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-[#0A0A0A]">
                <AlertTriangle className="w-5 h-5 text-[#E10600]" />
                Alertas Ativos
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {getActiveAlerts().length > 0 ? (
                getActiveAlerts().map(alert => (
                  <div key={alert.id} className="p-4 bg-[#FFF3C4] rounded-xl border border-[#E6C85C]">
                    <div className="flex items-start justify-between">
                      <div className="flex items-start gap-3">
                        <div className={`w-3 h-3 rounded-full mt-1 ${
                          alert.type === 'assessment_due' ? 'bg-[#1FBF75]' :
                          alert.type === 'payment_due' ? 'bg-[#E10600]' :
                          'bg-[#FFC300]'
                        }`}></div>
                        <div>
                          <p className="font-medium text-[#0A0A0A]">{alert.message}</p>
                          <p className="text-sm text-[#4A4A4A]">
                            Data: {new Date(alert.targetDate).toLocaleDateString('pt-BR')}
                          </p>
                        </div>
                      </div>
                      <Button
                        size="sm"
                        onClick={() => {
                          setAlerts(prev => prev.map(a => 
                            a.id === alert.id ? { ...a, isActive: false } : a
                          ));
                        }}
                        className="bg-[#4A4A4A] hover:bg-[#2A2A2A] text-white rounded-xl"
                      >
                        <CheckCircle className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-8">
                  <Bell className="w-12 h-12 text-[#4A4A4A] mx-auto mb-4" />
                  <p className="text-[#4A4A4A]">Nenhum alerta ativo</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Configurações de Alertas */}
          <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-[#0A0A0A]">
                <Settings className="w-5 h-5 text-[#FFC300]" />
                Configurações de Alertas
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label className="text-[#0A0A0A] font-medium">
                    Lembrete de Avaliação Física (dias de antecedência)
                  </Label>
                  <Input
                    type="number"
                    value={alertSettings.assessmentReminder}
                    onChange={(e) => setAlertSettings(prev => ({
                      ...prev,
                      assessmentReminder: parseInt(e.target.value)
                    }))}
                    className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-[#0A0A0A] font-medium">
                    Lembrete de Pagamento (dias de antecedência)
                  </Label>
                  <Input
                    type="number"
                    value={alertSettings.paymentReminder}
                    onChange={(e) => setAlertSettings(prev => ({
                      ...prev,
                      paymentReminder: parseInt(e.target.value)
                    }))}
                    className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-[#0A0A0A] font-medium">
                    Lembrete de Treino (dias de antecedência)
                  </Label>
                  <Input
                    type="number"
                    value={alertSettings.trainingReminder}
                    onChange={(e) => setAlertSettings(prev => ({
                      ...prev,
                      trainingReminder: parseInt(e.target.value)
                    }))}
                    className="border-2 border-[#E6C85C] rounded-xl focus:border-[#FFC300]"
                  />
                </div>

                <div className="flex items-center justify-between p-4 bg-[#FFF3C4] rounded-xl border border-[#E6C85C]">
                  <div>
                    <p className="font-medium text-[#0A0A0A]">Notificações Push</p>
                    <p className="text-sm text-[#4A4A4A]">Receber notificações no app</p>
                  </div>
                  <Button
                    onClick={() => setAlertSettings(prev => ({
                      ...prev,
                      enableNotifications: !prev.enableNotifications
                    }))}
                    className={`${
                      alertSettings.enableNotifications 
                        ? 'bg-[#1FBF75] text-white' 
                        : 'bg-[#4A4A4A] text-white'
                    } rounded-xl`}
                  >
                    {alertSettings.enableNotifications ? 'Ativado' : 'Desativado'}
                  </Button>
                </div>
              </div>

              <Button
                className="w-full bg-[#1FBF75] hover:bg-[#1AA366] text-white font-semibold py-3 rounded-2xl"
              >
                <Save className="w-5 h-5 mr-2" />
                Salvar Configurações
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Calendar className="w-6 h-6 text-[#FFC300]" />
          <h2 className="text-2xl font-bold text-white">Agenda</h2>
        </div>
        <div className="flex gap-3">
          <Button
            onClick={() => setActiveView('alerts')}
            className="bg-[#E10600] hover:bg-[#C00000] text-white rounded-xl relative"
          >
            <Bell className="w-4 h-4 mr-2" />
            Alertas
            {getActiveAlerts().length > 0 && (
              <Badge className="absolute -top-2 -right-2 bg-[#FFC300] text-[#0A0A0A] w-6 h-6 rounded-full p-0 flex items-center justify-center text-xs">
                {getActiveAlerts().length}
              </Badge>
            )}
          </Button>
          <Button
            onClick={() => setActiveView('new')}
            className="bg-[#1FBF75] hover:bg-[#1AA366] text-white rounded-xl"
          >
            <Plus className="w-4 h-4 mr-2" />
            Novo Compromisso
          </Button>
        </div>
      </div>

      {/* Controles de Navegação e Visualização */}
      <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button
                onClick={() => navigateDate('prev')}
                className="bg-[#FFC300] hover:bg-[#E6C85C] text-[#0A0A0A] rounded-xl"
              >
                <ChevronLeft className="w-4 h-4" />
              </Button>
              
              <h3 className="text-xl font-bold text-[#0A0A0A]">
                {viewMode === 'month' && selectedDate.toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' })}
                {viewMode === 'week' && `Semana de ${selectedDate.toLocaleDateString('pt-BR')}`}
                {viewMode === 'day' && formatDate(selectedDate)}
              </h3>
              
              <Button
                onClick={() => navigateDate('next')}
                className="bg-[#FFC300] hover:bg-[#E6C85C] text-[#0A0A0A] rounded-xl"
              >
                <ChevronRight className="w-4 h-4" />
              </Button>
            </div>

            <div className="flex items-center gap-2">
              <Tabs value={viewMode} onValueChange={(value) => setViewMode(value as 'day' | 'week' | 'month')}>
                <TabsList className="bg-[#FFF3C4] border border-[#E6C85C] rounded-xl">
                  <TabsTrigger value="day" className="data-[state=active]:bg-[#FFC300] rounded-lg">
                    Dia
                  </TabsTrigger>
                  <TabsTrigger value="week" className="data-[state=active]:bg-[#FFC300] rounded-lg">
                    Semana
                  </TabsTrigger>
                  <TabsTrigger value="month" className="data-[state=active]:bg-[#FFC300] rounded-lg">
                    Mês
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Filtros */}
      <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
        <CardContent className="p-4">
          <div className="flex items-center gap-4">
            <Filter className="w-5 h-5 text-[#FFC300]" />
            <div className="flex items-center gap-4 flex-1">
              <div className="flex items-center gap-2">
                <Label className="text-[#0A0A0A] font-medium">Tipo:</Label>
                <select
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value)}
                  className="p-2 border border-[#E6C85C] rounded-lg bg-white"
                >
                  <option value="all">Todos</option>
                  <option value="training_session">Treinos</option>
                  <option value="physical_assessment">Avaliações</option>
                  <option value="online_consultation">Consultorias</option>
                  <option value="payment_due">Pagamentos</option>
                </select>
              </div>
              
              <div className="flex items-center gap-2">
                <Label className="text-[#0A0A0A] font-medium">Aluno:</Label>
                <select
                  value={filterStudent}
                  onChange={(e) => setFilterStudent(e.target.value)}
                  className="p-2 border border-[#E6C85C] rounded-lg bg-white"
                >
                  <option value="all">Todos</option>
                  <option value="1">João Silva</option>
                  <option value="2">Maria Santos</option>
                  <option value="3">Pedro Costa</option>
                </select>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Visualização do Calendário */}
      <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
        <CardContent className="p-6">
          {renderCalendarView()}
        </CardContent>
      </Card>

      {/* Lista de Próximos Compromissos */}
      <Card className="bg-white border-2 border-[#E6C85C] shadow-lg rounded-2xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-3 text-[#0A0A0A]">
            <CalendarDays className="w-5 h-5 text-[#FFC300]" />
            Próximos Compromissos
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {getFilteredAppointments()
            .filter(appointment => new Date(appointment.date) >= new Date())
            .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
            .slice(0, 5)
            .map(appointment => (
              <div key={appointment.id} className="flex items-center justify-between p-4 bg-[#FFF3C4] rounded-xl border border-[#E6C85C]">
                <div className="flex items-center gap-4">
                  <div className={`w-4 h-4 rounded-full ${typeColors[appointment.type]}`}></div>
                  <div>
                    <h4 className="font-semibold text-[#0A0A0A]">{appointment.studentName}</h4>
                    <p className="text-sm text-[#4A4A4A]">
                      {new Date(appointment.date).toLocaleDateString('pt-BR')} às {appointment.startTime}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge className={`${typeColors[appointment.type]} text-white`}>
                    {typeLabels[appointment.type]}
                  </Badge>
                  <Badge className={`${statusColors[appointment.status]} text-white`}>
                    {statusLabels[appointment.status]}
                  </Badge>
                  <Button
                    size="sm"
                    onClick={() => handleEdit(appointment)}
                    className="bg-[#FFC300] hover:bg-[#E6C85C] text-[#0A0A0A] rounded-xl"
                  >
                    <Edit className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            ))}
          
          {getFilteredAppointments().filter(appointment => new Date(appointment.date) >= new Date()).length === 0 && (
            <div className="text-center py-8">
              <Calendar className="w-12 h-12 text-[#4A4A4A] mx-auto mb-4" />
              <p className="text-[#4A4A4A]">Nenhum compromisso agendado</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}